default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: nhc
  password: 1
  host: localhost
  port: 5432

development:
  <<: *default
  database: blog_develop

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
