<<<<<<< HEAD
avatar_default: "avt_default.jpg"

post:
  picture_default: "post.jpg"
  date: "%B %d, %Y"
  maximum_title: 100
rate:
  minimum_rate: 1
  maximum_rate: 5
=======
picture_default: "post.jpg"
>>>>>>> c312721... signup-login-edit-user
